### ISSUE TITLE
app no work

### ISSUE THREAD

**Issue by matt-malarkey** [Tiger-Cross/Good-Ideas-Machine#1]
Please add firebase plist to the Xcode project so I can run this thank you xxx ❣️

(https://firebase.google.com/docs/flutter/setup step 3)

**Comment by Tiger-Cross** [comment]
Not gonna add it to the repo just yet while it's still in dev I'm afraid mate. Create yourself a firebase project if you'd like to give it a go ;)

**Comment by matt-malarkey** [comment]
Ah that's sad, fair enough
